### ISSUE TITLE
Phase 0: Minimum Viable Network (Pong)

### ISSUE THREAD

**Issue by justmoon** [interledger-deprecated/interledger#7]
* [ ] Liquidity Parameters #10 
* [ ] Plugin XRP RTS
* [x] Segmented ILP Prefixes (fixed in interledgerjs/ilp-connector#416)
* [ ] All-in-one ILP toolkit (interledgerjs/ilp#130)
* [x] Finalize PSK
* [x] Error Codes (interledger/rfcs#397)
* [ ] Bandwidth Limit
* [x] Update to ILPv4 (interledgerjs/ilp-connector#401, interledgerjs/ilp#122)
* [x] Update Routing (interledgerjs/ilp-connector#416)

**Comment by emschwartz** [comment]
What are the Liquidity Parameters?

Is Plugin XRP RTS different from XRP PayChan?

What is the All-in-one ILP toolkit? Is that a continuation of ILP-Kit or something else?

Does https://github.com/interledger/rfcs/issues/397 resolve the "Error Codes" bullet point?

**Comment by justmoon** [comment]
> What are the Liquidity Parameters?

Broke this out into a ticket: #10 

> Is Plugin XRP RTS different from XRP PayChan?

@sharafian Do you remember what that bullet was referring to?

> What is the All-in-one ILP toolkit? Is that a continuation of ILP-Kit or something else?

It's a new version of the ILP module which contains the latest suite of protocols and has a sensible API and defaults. Added an issue for that.

> Does interledger/rfcs#397 resolve the "Error Codes" bullet point?

I think so, yeah. Added a link to the issue.

**Comment by sharafian** [comment]
> @sharafian Do you remember what that bullet was referring to?

Probably means Reliable Transaction Submission

**Comment by sharafian** [comment]
Checked error codes and update routing, because those issues/PRs have been resolved

**Comment by sharafian** [comment]
@dappelt Is there anything left to be done on Plugin XRP Reliable Transaction Submission? I saw that all the txsubmitter related PRs were merged

**Comment by dappelt** [comment]
The original feature set is merged and all plugins are updated to use the new transaction submitter module. Since then I worked on some additional features: 1) Transaction Persistence and 2) Retry strategy. We should have a call and discuss these in more detail.
